POST  http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1heWFuayIsImlkIjoiNWYzZjExMjg5MWVkMmUzOTA4MzU0ODBjIiwiaWF0IjoxNTk3OTY5NTIxfQ.5Ab1w8d8c9TP3BxUH6V9SC7oCWYSG-8_1JtJeuRsPAs

{
        "title": "bruh",
        "author": "bugbruh",
        "url": "https://reactpatterns.com/",
        "likes": 1117,
        "user": "mayank"
}